-- =============================================================================
-- seed.sql — local-only demo data (runs on `supabase db reset`).
--
-- The WBS reference tree now ships as a MIGRATION (0009_seed_wbs_reference.sql),
-- so it is applied to every environment via `supabase db push` — it is NOT
-- repeated here. Use this file only for local development convenience.
--
-- To load the real Sunny project locally, apply the generated import after reset:
--   psql "$DATABASE_URL" -f data/sunny_affordable/seed_sunny_affordable.sql
--
-- Example (commented): seed the three PKB spec levels for a given org.
-- -----------------------------------------------------------------------------
-- insert into spec_levels (org_id, level, target_psf_low, target_psf_high, description) values
--   ('<ORG_UUID>', 'essential', 165, 180, 'Entrada / investidor / aluguel'),
--   ('<ORG_UUID>', 'signature', 200, 225, 'Padrão PKB / cliente final'),
--   ('<ORG_UUID>', 'luxury',    245, 280, 'Alto padrão / custom')
-- on conflict (org_id, level, base_model, county) do nothing;
