#!/usr/bin/env node
// =============================================================================
// build_seed.mjs — turn what the collectors gathered into one idempotent SQL
// file for the `ops` schema (paste it into the Supabase SQL editor, or run it
// with psql on the server).
//
//   node scripts/build_seed.mjs > data/seed_ops.sql
//
// Sources:
//   data/permits/permits_control_*.csv   the Permits Control spreadsheet (jobs)
//   data/buildertrend/jobpicker_raw.json Buildertrend jobs (ids, names, owners)
//   data/portal/<county>/*.json          EnerGov permits (rounds, reviews, inspections, holds)
//
// The org is looked up by name (OPS_ORG_NAME, default "PKB Homes"; not the demo org). Re-running is
// safe: every insert is an upsert on a natural key, and events use dedupe_key.
// =============================================================================
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const csvPath = join(ROOT, 'data', 'permits', readdirSync(join(ROOT, 'data', 'permits')).filter(f => f.endsWith('.csv')).sort().pop());

// Spreadsheet rows whose building-permit number differs from the one the portal uses.
const PERMIT_OVERRIDES = { '49': { number: 'BLDR-2026-0437', portal: 'energov:winterpark' } }; // BOA-2026-0004 is the Board of Adjustment case

const q = (v) => v == null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const qd = (v) => q(toDate(v));
const qn = (v) => { const n = Number(String(v ?? '').replace(/[$,\s]/g, '')); return Number.isFinite(n) && String(v ?? '').trim() !== '' ? String(n) : 'null'; };
const qarr = (a) => a && a.length ? `array[${a.map(q).join(',')}]::text[]` : `'{}'::text[]`;
function toDate(v) {
  const s = String(v ?? '').trim();
  if (!s || s === '-' || /^n\/?a$/i.test(s)) return null;
  if (/^\d{4}-\d{2}-\d{2}/.test(s)) return s.slice(0, 10);
  const m = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/);
  if (!m) return null;
  const y = m[3].length === 2 ? '20' + m[3] : m[3];
  return `${y}-${m[1].padStart(2, '0')}-${m[2].padStart(2, '0')}`;
}
function parseCsv(text) {
  const rows = []; let row = [], f = '', inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) { if (c === '"') { if (text[i + 1] === '"') { f += '"'; i++; } else inQ = false; } else f += c; }
    else if (c === '"') inQ = true; else if (c === ',') { row.push(f); f = ''; }
    else if (c === '\n') { row.push(f); rows.push(row); row = []; f = ''; } else if (c !== '\r') f += c;
  }
  if (f || row.length) { row.push(f); rows.push(row); }
  const h = rows[0].map(s => s.trim());
  return rows.slice(1).filter(r => r[0] && /^\d+$/.test(r[0].trim())).map(r => Object.fromEntries(h.map((k, i) => [k, (r[i] ?? '').trim()])));
}

const STATUS = { 'Completed': 'completed', 'Construction': 'construction', 'Licensing': 'licensing', 'Starting Process': 'starting', 'Stand-By': 'stand_by', 'Turtle': 'licensing' };
const PORTAL_OF_COUNTY = { Marion: 'energov:marion', Citrus: 'accela:citrus', Orange: 'fasttrack:orange', Charlotte: 'charlotte', Sarasota: 'sarasota', Lake: 'lake' };

const out = [];
const w = (s) => out.push(s);
w('-- Generated by ops/scripts/build_seed.mjs on ' + new Date().toISOString());
w('begin;');
w(`create temp table _org on commit drop as select id from public.orgs where name = ${q(process.env.OPS_ORG_NAME || 'PKB Homes')} limit 1;`);
w(`do $$ begin if not exists (select 1 from _org) then raise exception 'org not found in public.orgs (set OPS_ORG_NAME)'; end if; end $$;`);

// ---- Buildertrend jobs by number ----
const bt = {};
const btFile = join(ROOT, 'data', 'buildertrend', 'jobpicker_raw.json');
if (existsSync(btFile)) {
  const find = (o) => { if (Array.isArray(o)) { if (o[0] && o[0].jobName) return o; for (const v of o) { const r = find(v); if (r) return r; } } else if (o && typeof o === 'object') for (const v of Object.values(o)) { const r = find(v); if (r) return r; } return null; };
  for (const j of find(JSON.parse(readFileSync(btFile, 'utf8'))) || []) { const m = String(j.jobName).match(/^(\d{4})\s*-/); if (m) bt[m[1]] = j; }
}
// Match spreadsheet rows to Buildertrend jobs by address (the spreadsheet '#' is
// not the Buildertrend job number). Key = house number + street core, e.g.
// "4730|142 pl"; for "TBD" lots the street core alone, used only if unique.
const ORD = /(\d+)(st|nd|rd|th)\b/g;
const SUFFIX = { street: 'st', st: 'st', lane: 'ln', ln: 'ln', place: 'pl', pl: 'pl', road: 'rd', rd: 'rd', avenue: 'ave', ave: 'ave', terrace: 'ter', ter: 'ter', circle: 'cir', cir: 'cir', court: 'ct', ct: 'ct', drive: 'dr', dr: 'dr', loop: 'loop', way: 'way', point: 'point', manor: 'mnr', mnr: 'mnr', trail: 'trl' };
function addrKey(a) {
  const s = String(a || '').toLowerCase().split(',')[0].replace(ORD, '$1').replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();
  const t = s.split(' ');
  const house = /^\d+$/.test(t[0]) ? t.shift() : (t[0] === 'tbd' ? (t.shift(), 'tbd') : 'tbd');
  const words = t.filter(w => !['sw', 'se', 'nw', 'ne', 'n', 's', 'e', 'w'].includes(w)).map(w => SUFFIX[w] || w);
  const core = words.slice(0, 2).join(' ');
  return { house, core, key: `${house}|${core}` };
}
const btByKey = {}, btByCore = {};
for (const j of Object.values(bt)) {
  const street = j.street || String(j.jobName).split(' - ').pop();
  const k = addrKey(street);
  (btByKey[k.key] ||= []).push(j);
  (btByCore[k.core] ||= []).push(j);
}
const normParcel = (p) => String(p || '').toUpperCase().replace(/[^0-9A-Z]/g, '');
const fieldsFile = join(ROOT, 'data', 'buildertrend', 'job_fields.json');
const btFields = existsSync(fieldsFile) ? JSON.parse(readFileSync(fieldsFile, 'utf8')).jobs : [];
const btByParcel = {};
for (const f of btFields) if (f.parcel) (btByParcel[normParcel(f.parcel)] ||= []).push(f);
const fieldsOf = (jobId) => btFields.find(f => f.jobId === jobId) || null;
function matchBtByParcel(parcel) {
  const hits = btByParcel[normParcel(parcel)] || [];
  if (hits.length !== 1) return null;
  return Object.values(bt).find(j => j.jobId === hits[0].jobId) || null;
}
function matchBt(address) {
  const k = addrKey(address);
  if (k.house !== 'tbd' && btByKey[k.key]?.length === 1) return btByKey[k.key][0];
  // Same house number and same street number/name ("5160 SW 165th Pl" vs "5160 SW 165TH").
  if (k.house !== 'tbd') {
    const first = k.core.split(' ')[0];
    const hits = Object.values(bt).filter(j => { const o = addrKey(j.street || j.jobName.split(' - ').pop()); return o.house === k.house && o.core.split(' ')[0] === first; });
    if (hits.length === 1) return hits[0];
  }
  const byCore = (btByCore[k.core] || []).filter(j => k.house === 'tbd' ? true : addrKey(j.street || j.jobName.split(' - ').pop()).house === k.house);
  return byCore.length === 1 ? byCore[0] : null;
}

// ---- Jobs from the spreadsheet ----
const rows = parseCsv(readFileSync(csvPath, 'utf8'));
const permitToJob = {};
const unmatched = [];
for (const r of rows) {
  // job_number = the Buildertrend number when matched, else "S" + spreadsheet row.
  // Parcel ID first (Buildertrend custom field "Parcial ID"), address as fallback.
  const b = (r.Parcel && matchBtByParcel(r.Parcel)) || matchBt(r.Address);
  const num = b ? String(b.jobName).slice(0, 4) : 'S' + r['#'].padStart(3, '0');
  if (!b) unmatched.push(`#${r['#']} ${r.Address}`);
  const turtle = r.Status === 'Turtle' || /turtle/i.test(r['Current Note']) ? 'relocation_pending' : 'none';
  w(`insert into ops.jobs (org_id, job_number, bt_job_id, bt_job_name, company, address, parcel, county, model, owner_name, contract_value, signed_at, first_draw_at, second_draw_at, status, turtle_state, note)
select id, ${q(num)}, ${b ? b.jobId : 'null'}, ${q(b?.jobName)}, ${q(r.Company === 'Prime' ? 'Prime' : 'PKB')}, ${q(r.Address)}, ${q(r.Parcel)}, ${q(r.County)}, ${q(r.Model)}, ${q(r.Owner)}, ${qn(r['Contract $'])}, ${qd(r['Signed Date'])}, ${qd(r['1st Draw'])}, ${qd(r['2nd Draw'])}, ${q(STATUS[r.Status] || 'starting')}, ${q(turtle)}, ${q(r['Current Note'])} from _org
on conflict (org_id, job_number) do update set bt_job_id = excluded.bt_job_id, bt_job_name = excluded.bt_job_name, company = excluded.company, address = excluded.address, parcel = excluded.parcel, county = excluded.county, model = excluded.model, owner_name = excluded.owner_name, contract_value = excluded.contract_value, signed_at = excluded.signed_at, first_draw_at = excluded.first_draw_at, second_draw_at = excluded.second_draw_at, status = excluded.status, turtle_state = excluded.turtle_state, note = excluded.note;`);
  // CO date ends monitoring for the job (see migration 0016).
  if (toDate(r.CO)) w(`update ops.jobs set co_at = ${qd(r.CO)} where org_id = (select id from _org) and job_number = ${q(num)};`);
  // Supervisor and project managers from Buildertrend (who gets inspection alerts).
  const bf = b ? fieldsOf(b.jobId) : null;
  if (bf) {
    const people = [...(bf.supervisor ? [['supervisor', bf.supervisor]] : []), ...[].concat(bf.projectManagers || []).filter(Boolean).map(n => ['pm', n])];
    w(`delete from ops.job_contacts where job_id = (select id from ops.jobs where org_id = (select id from _org) and job_number = ${q(num)}) and role in ('supervisor', 'pm');`);
    for (const [role, name] of people) w(`insert into ops.job_contacts (org_id, job_id, role, name) select j.org_id, j.id, ${q(role)}, ${q(name)} from ops.jobs j join _org o on o.id = j.org_id where j.job_number = ${q(num)};`);
  }
  // Building permit case from the spreadsheet (portal data overlays it below).
  const ov = PERMIT_OVERRIDES[r['#']];
  const number = ov?.number || (r['Permit N'] && r['Permit N'] !== '-' ? r['Permit N'] : null) || bf?.permit || null;
  if (number) {
    const portal = ov?.portal || PORTAL_OF_COUNTY[r.County] || null;
    permitToJob[number] = num;
    w(`insert into ops.permit_cases (org_id, job_id, kind, portal, number, applied_at, issued_at, tracked_by, ops_status)
select j.org_id, j.id, 'building', ${q(portal)}, ${q(number)}, ${qd(r['BP Filled'])}, ${qd(r['BP Issued'])}, ${q(r.Model === 'Custom' ? 'pkb' : 'designer')}, ${q(toDate(r['BP Issued']) ? 'issued' : toDate(r['BP Filled']) ? 'in_review' : 'requested')}
from ops.jobs j join _org o on o.id = j.org_id where j.job_number = ${q(num)}
on conflict (org_id, portal, number) where number is not null do nothing;`);
  }
  // Septic permit case (issued date only is tracked in the spreadsheet).
  if (toDate(r['SP Issued'])) {
    w(`insert into ops.permit_cases (org_id, job_id, kind, portal, number, issued_at, ops_status)
select j.org_id, j.id, 'septic', 'fdep', ${q('SEPTIC-' + num)}, ${qd(r['SP Issued'])}, 'issued'
from ops.jobs j join _org o on o.id = j.org_id where j.job_number = ${q(num)}
on conflict (org_id, portal, number) where number is not null do nothing;`);
  }
  // Pauses the spreadsheet notes describe.
  const note = r['Current Note'] || '';
  const pause = /waiting 1st draw/i.test(note) ? 'awaiting_1st_draw' : /impact fee/i.test(note) ? 'awaiting_impact_fees' : /warranty deed/i.test(note) ? 'awaiting_warranty_deed' : /sinal verde|green light/i.test(note) ? 'owner_deferred_start' : null;
  if (pause) {
    w(`insert into ops.job_pauses (org_id, job_id, reason, started_at, note)
select j.org_id, j.id, ${q(pause)}, current_date, ${q(note)} from ops.jobs j join _org o on o.id = j.org_id where j.job_number = ${q(num)}
and not exists (select 1 from ops.job_pauses p where p.job_id = j.id and p.reason = ${q(pause)} and p.ended_at is null);`);
  }
}

// ---- Portal data (EnerGov) ----
const portalDir = join(ROOT, 'data', 'portal');
for (const county of existsSync(portalDir) ? readdirSync(portalDir) : []) {
  const portal = `energov:${county}`;
  for (const f of readdirSync(join(portalDir, county)).filter(f => f.endsWith('.json') && !f.startsWith('_'))) {
    const d = JSON.parse(readFileSync(join(portalDir, county, f), 'utf8'));
    if (!d.found) continue;
    const p = d.permit;
    // Number rounds by date here: older snapshots carry EnerGov's per-step VersionNumber instead.
    p.submittals = [...p.submittals].sort((a, b) => (a.submittedAt || '').localeCompare(b.submittedAt || '')).map((s, i) => ({ ...s, round: i + 1 }));
    const roundOf = Object.fromEntries(p.submittals.map(s => [s.submittalId, s.round]));
    p.reviewItems = p.reviewItems.map(r => ({ ...r, round: roundOf[r.submittalId] ?? null }));
    const num = permitToJob[p.number];
    if (!num) continue; // permit not in the spreadsheet
    const caseSel = `(select id from ops.permit_cases where org_id = (select id from _org) and portal = ${q(portal)} and number = ${q(p.number)})`;
    const lastSub = p.submittals[p.submittals.length - 1];
    const ops = p.issuedAt ? 'issued' : /fees? due/i.test(p.status) ? 'fees_due' : lastSub && /re-?submit/i.test(lastSub.status) ? 'corrections' : 'in_review';
    const ball = p.issuedAt ? null : ops === 'corrections' ? 'sovereign' : ops === 'fees_due' ? 'pkb' : 'county';
    w(`update ops.permit_cases set portal_case_id = ${q(p.caseId)}, portal_status = ${q(p.status)}, ops_status = ${q(ops)}, ball_with = ${q(ball)}, applied_at = coalesce(${qd(p.appliedAt)}, applied_at), issued_at = coalesce(${qd(p.issuedAt)}, issued_at), expires_at = ${qd(p.expiresAt)}, finaled_at = ${qd(p.finalizedAt)}, valuation = ${qn(p.valuation)}, square_feet = ${qn(p.squareFeet)}, fee_total = ${qn(p.feeSummary?.TotalFee)}, fee_unpaid = ${qn(p.feeSummary?.TotalUnpaidFee)}, last_collected_at = ${q(p.collectedAt)} where id = ${caseSel};`);
    for (const s of p.submittals) {
      w(`insert into ops.submittals (org_id, permit_case_id, portal_id, round, type, status, submitted_at, due_at, completed_at) select (select id from _org), ${caseSel}, ${q(s.submittalId)}, ${s.round}, ${q(s.type)}, ${q(s.status)}, ${qd(s.submittedAt)}, ${qd(s.dueAt)}, ${qd(s.completedAt)}
on conflict (permit_case_id, round) do update set status = excluded.status, completed_at = excluded.completed_at;`);
    }
    for (const r of p.reviewItems) {
      const failed = /re-?submit|denied|fail/i.test(r.status || '');
      w(`insert into ops.review_items (org_id, permit_case_id, submittal_id, portal_id, round, department, status, failed, reviewer, reviewer_email, due_at, completed_at, comments)
select (select id from _org), ${caseSel}, (select id from ops.submittals where permit_case_id = ${caseSel} and round = ${r.round ?? 'null'}), ${q(r.itemReviewId)}, ${r.round ?? 'null'}, ${q(r.department)}, ${q(r.status)}, ${failed}, ${q(r.assignedTo)}, ${q(r.assignedToEmail)}, ${qd(r.dueAt)}, ${qd(r.completedAt)}, ${q(r.comments)}
on conflict (permit_case_id, portal_id) do update set status = excluded.status, failed = excluded.failed, completed_at = excluded.completed_at, comments = excluded.comments;`);
      if (r.completedAt) {
        w(`insert into ops.events (org_id, job_id, permit_case_id, kind, source, occurred_at, payload, dedupe_key)
select c.org_id, c.job_id, c.id, ${q(failed ? 'review_item.failed' : 'review_item.approved')}, 'import', ${q(r.completedAt)}::timestamptz, ${q(JSON.stringify({ department: r.department, round: r.round, status: r.status }))}::jsonb, ${q(`energov:review_item:${r.itemReviewId}:${r.status}`)}
from ops.permit_cases c where c.id = ${caseSel} on conflict (org_id, dedupe_key) do nothing;`);
      }
    }
    for (const i of p.inspections) {
      // Status text wins over the portal flags: EnerGov sets IsSuccessFlag on "Disapproved - no fees".
      const st = i.status || '';
      const failed = /disapprov|fail|partial|denied/i.test(st) || (!!i.failed && !/^(approved|passed)/i.test(st));
      const passed = !failed && (/^(approved|passed)/i.test(st) || (!!i.passed && !st));
      w(`insert into ops.inspections (org_id, permit_case_id, number, type, status, passed, failed, reinspection, requested_at, scheduled_at, actual_at, inspector, comments)
select (select id from _org), ${caseSel}, ${q(i.number)}, ${q(i.type)}, ${q(i.status)}, ${passed}, ${failed}, ${!!i.reinspection}, ${qd(i.requestedAt)}, ${qd(i.scheduledAt)}, ${qd(i.actualAt)}, ${q(i.inspector)}, ${q(i.comments || null)}
on conflict (permit_case_id, number) do update set status = excluded.status, passed = excluded.passed, failed = excluded.failed, actual_at = excluded.actual_at, comments = coalesce(excluded.comments, ops.inspections.comments);`);
    }
    for (const h of p.holds) {
      const key = `${h.name}|${h.createdAt}|${(h.comments || '').slice(0, 40)}`;
      w(`insert into ops.holds (org_id, permit_case_id, portal_id, name, type, blocking, reason, comments, created_at, active)
select (select id from _org), ${caseSel}, ${q(key)}, ${q(h.name)}, ${q(h.type)}, ${/stop/i.test(h.type || '')}, ${q(h.reason)}, ${q(h.comments)}, ${qd(h.createdAt)}, ${!!h.active}
on conflict (permit_case_id, portal_id) do update set active = excluded.active;`);
    }
  }
}

w('commit;');
// --parts N: write data/seed_ops_partK.sql files of ~250 KB, each a self-contained
// transaction (small enough for the Supabase SQL editor). Otherwise print to stdout.
const header = out.slice(0, 4), body = out.slice(4, -1);
if (process.argv.includes('--parts')) {
  const { writeFileSync, mkdirSync } = await import('node:fs');
  const dir = join(ROOT, 'data', 'seed'); mkdirSync(dir, { recursive: true });
  const parts = []; let cur = [], size = 0;
  for (const stmt of body) { cur.push(stmt); size += stmt.length; if (size > 250000) { parts.push(cur); cur = []; size = 0; } }
  if (cur.length) parts.push(cur);
  parts.forEach((ps, i) => writeFileSync(join(dir, `seed_ops_part${String(i + 1).padStart(2, '0')}.sql`), [...header, ...ps, 'commit;'].join('\n') + '\n'));
  console.error(`wrote ${parts.length} parts to data/seed/`);
} else console.log(out.join('\n'));
console.error(`jobs matched to Buildertrend: ${rows.length - unmatched.length}/${rows.length}` + (unmatched.length ? `\nunmatched:\n  ${unmatched.join('\n  ')}` : ''));
