#!/usr/bin/env node
// =============================================================================
// import_estimate.mjs — turn a normalized estimate folder into idempotent SQL.
//
// Usage:
//   node scripts/import_estimate.mjs <folder> [--org-name "..."] > out.sql
//
// A <folder> holds two files (the canonical intermediate format that PDF/XLSX/
// Buildertrend imports all normalize into):
//   project.json   — org + project + estimate metadata (see data/sunny_affordable)
//   estimate.csv   — columns: line_code,wbs_code,item_name,qty,unit,unit_cost
//
// The generated SQL is safe to re-run: it upserts the org/project/estimate by
// their fixed UUIDs and replaces the estimate's line items wholesale.
//
// It also reconciles the CSV against estimate.total_expected and prints the
// result as a SQL comment (and to stderr), so a mismatch is loud, not silent.
// =============================================================================

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const folder = process.argv[2];
if (!folder) {
  console.error('usage: node scripts/import_estimate.mjs <folder> [--org-name "..."]');
  process.exit(2);
}
const orgNameFlag = (() => {
  const i = process.argv.indexOf('--org-name');
  return i > -1 ? process.argv[i + 1] : null;
})();

// ---- tiny RFC4180-ish CSV parser (handles quotes + embedded commas) --------
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c === '\r') { /* skip */ }
    else field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.length > 1 || (r.length === 1 && r[0] !== ''));
}

const sqlStr = (s) => (s === null || s === undefined) ? 'null' : `'${String(s).replace(/'/g, "''")}'`;
const sqlNum = (n) => (n === null || n === undefined || n === '') ? 'null' : String(n);

// ---- load inputs -----------------------------------------------------------
const meta = JSON.parse(readFileSync(join(folder, 'project.json'), 'utf8'));
const csv = parseCsv(readFileSync(join(folder, 'estimate.csv'), 'utf8'));
const header = csv[0].map(h => h.trim());
const need = ['line_code', 'wbs_code', 'item_name', 'qty', 'unit', 'unit_cost'];
for (const col of need) if (!header.includes(col)) throw new Error(`estimate.csv missing column: ${col}`);
const idx = Object.fromEntries(header.map((h, i) => [h, i]));

const items = csv.slice(1).map((r, n) => ({
  line_code: r[idx.line_code].trim(),
  wbs_code:  r[idx.wbs_code].trim(),
  item_name: r[idx.item_name].trim(),
  qty:       Number(r[idx.qty]),
  unit:      r[idx.unit].trim().toLowerCase(),
  unit_cost: Number(r[idx.unit_cost]),
  sort:      n + 1,
}));

// ---- reconcile -------------------------------------------------------------
const computed = items.reduce((s, it) => s + it.qty * it.unit_cost, 0);
const expected = meta.estimate?.total_expected;
const round2 = (x) => Math.round(x * 100) / 100;
const ok = expected == null ? null : round2(computed) === round2(expected);
const reconMsg = expected == null
  ? `sum(qty*unit_cost) = ${round2(computed)} (no total_expected to check)`
  : `sum(qty*unit_cost) = ${round2(computed)} vs expected ${round2(expected)} => ${ok ? 'MATCH' : 'MISMATCH'}`;
console.error(`[reconcile] ${folder}: ${reconMsg} · ${items.length} line items`);

const org = meta.org, p = meta.project, e = meta.estimate;
const orgName = orgNameFlag || org.name;

// ---- emit SQL --------------------------------------------------------------
const out = [];
out.push(`-- Generated by scripts/import_estimate.mjs from ${folder}`);
out.push(`-- ${reconMsg}`);
if (ok === false) out.push(`-- WARNING: reconciliation MISMATCH — review estimate.csv before trusting this import.`);
out.push(`begin;`);
out.push(`insert into orgs (id, name) values (${sqlStr(org.id)}, ${sqlStr(orgName)})`);
out.push(`  on conflict (id) do update set name = excluded.name;`);
out.push('');
out.push(`insert into projects (id, org_id, name, base_model, county, address, market,`);
out.push(`    living_area_sf, total_area_sf, wind_speed_mph, flood_zone, water, sewer, contract, initial_level, arv)`);
out.push(`  values (${sqlStr(p.id)}, ${sqlStr(org.id)}, ${sqlStr(p.name)}, ${sqlStr(p.base_model)}, ${sqlStr(p.county)},`);
out.push(`    ${sqlStr(p.address)}, ${sqlStr(p.market)}, ${sqlNum(p.living_area_sf)}, ${sqlNum(p.total_area_sf)},`);
out.push(`    ${sqlNum(p.wind_speed_mph)}, ${sqlStr(p.flood_zone)}, ${p.water ? sqlStr(p.water) : 'null'}::water_source,`);
out.push(`    ${p.sewer ? sqlStr(p.sewer) : 'null'}::sewer_type, ${p.contract ? sqlStr(p.contract) : 'null'}::contract_type,`);
out.push(`    ${p.initial_level ? sqlStr(p.initial_level) : 'null'}::spec_level, ${sqlNum(p.arv)})`);
out.push(`  on conflict (id) do update set`);
out.push(`    name=excluded.name, base_model=excluded.base_model, county=excluded.county, market=excluded.market,`);
out.push(`    living_area_sf=excluded.living_area_sf, total_area_sf=excluded.total_area_sf,`);
out.push(`    wind_speed_mph=excluded.wind_speed_mph, flood_zone=excluded.flood_zone, water=excluded.water,`);
out.push(`    sewer=excluded.sewer, contract=excluded.contract, initial_level=excluded.initial_level, arv=excluded.arv;`);
out.push('');
out.push(`insert into estimates (id, org_id, project_id, level, version, status, notes)`);
out.push(`  values (${sqlStr(e.id)}, ${sqlStr(org.id)}, ${sqlStr(p.id)}, ${sqlStr(e.level)}::spec_level,`);
out.push(`    ${sqlNum(e.version ?? 1)}, ${sqlStr(e.status ?? 'draft')}::estimate_status,`);
out.push(`    ${sqlStr(`Imported ${e.source_file ?? ''} (${e.estimate_date ?? ''}).`)})`);
out.push(`  on conflict (id) do update set level=excluded.level, status=excluded.status, notes=excluded.notes;`);
out.push('');
out.push(`-- Replace this estimate's line items wholesale (idempotent re-import).`);
out.push(`delete from estimate_items where estimate_id = ${sqlStr(e.id)};`);
out.push(`insert into estimate_items (org_id, estimate_id, wbs_code, line_code, description, qty, unit, unit_cost, price_source, sort_order) values`);
out.push(items.map(it =>
  `  (${sqlStr(org.id)}, ${sqlStr(e.id)}, ${sqlStr(it.wbs_code)}, ${sqlStr(it.line_code)}, ${sqlStr(it.item_name)}, ` +
  `${sqlNum(it.qty)}, ${sqlStr(it.unit)}::unit_type, ${sqlNum(it.unit_cost)}, 'catalog'::price_source, ${it.sort})`
).join(',\n') + ';');
out.push(`commit;`);
console.log(out.join('\n'));
